title: '[DATA EXPUNGED]'
category: reverse
author: max_stierlitz
description: During the capture of an [DATA EXPUNGED], CSP Foundation found this artifact. Can you help them solve this mystery?
flag: nto{f0und4ti0n_th4nks_y0u_1_k0shk0_zh3na_v_p0d4rok}
