title: sc
category: web
author: bavette_13
description: |
  Нашел формочку бота, так и не придумал что с ней можно сделать.

  [http://sc.mephictf.ru:5999](http://sc.mephictf.ru:5999)
flag: nto{5dfd01abc18ec490ed3ab8e5a4964795}

