title: Amazeng
category: misc
author: tarasovion
description: |
  ...вы просыпаетесь в темном сыром помещении. Вокруг вас почти ничего не видно. Только тонкий
  лучик света светит откуда-то из-за угла. Проследовав за ним по узкому коридору вы переходите
  в другое помещение, по размеру напоминающее первое. В этот раз у вас уже не один маршрут – из
  этой комнаты есть два выхода. Вас посещает мысль о том, что вы, должно быть, в лабиринте. Благо
  он оказался небольшим – спустя около часа скитаний вы видите яркий свет. “Выход!” – воскликнули
  вы, устремившись навстречу свету. Однако, выйдя из лабиринта… вы просыпаетесь в темном сыром
  помещении.

  Все буквы во флаге - прописные (маленькие)!

  `nc misc.mephictf.ru 8888`
flag: nto{i_4m_s1ck_0f_bfs_m4ze_t4sk5_0n_ctfs..._w4it_a_m1nu73!!}
