services:
  street-racing:
    build: .
    container_name: street-racing
    ports:
      - 80:3000
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512M"
          pids: 512
      restart_policy:
        condition: always
    read_only: true
