#!/usr/bin/env sh

export PATH=/bin:/sbin:/usr/bin:/usr/sbin
mdev -s
mount -t proc none /proc
mkdir -p /dev/pts
mount -vt devpts -o gid=4,mode=620 none /dev/pts
chmod 666 /dev/ptmx
stty -opost

echo 2 > /proc/sys/kernel/kptr_restrict
#echo 1 > /proc/sys/kernel/dmesg_restrict
insmod /vuln.ko
#


mknod -m 666 /dev/kernull c `grep kernull /proc/devices | awk '{print $1;}'` 0

setsid setuidgid 1228 sh

umount /proc
poweroff -d 0 -f
