services:
  collaidos:
    build: .
    container_name: collaidos
    environment:
      - FLAG=nto{th3_r34l_ha5h_c0ll15i0n_w4s_7h3_fr1end5_we_m4de_a1on9_7h3_w4y}
    ports:
      - 5000:5000
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "256M"
          pids: 256
      restart_policy:
        condition: always
    read_only: true
